### ISSUE TITLE
Documentation: Clarification question about the aim of the project

### ISSUE THREAD

**Issue by hhzl** [BrandonRomano/static-lite#22]
Hello
A question regarding the aim of the project:

If you write [easy to understand](https://github.com/BrandonRomano/static-lite/blob/master/project_objectives.md#easy-to-understand) you are mainly refering to the ``scripts`` section of the ``package.json`` file 
https://github.com/BrandonRomano/static-lite/blob/master/package.json#L65

So the project is about something such as here
https://gablaxian.com/blog/using-npm-as-a-build-tool
which refers to this one
https://www.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/
?

**Comment by BrandonRomano** [comment]
Hey @hhzl -- Yes that is correct.  Everything this library does occurs from the npm scripts.  The two articles that you've shared describe the approach this library takes.

This library takes advantage of the provided CLIs of other tools, and the npm scripts are simply the glue that puts it all together.

Let me know if that answers your question!

**Comment by hhzl** [comment]
Yes,  thank you for the confirmation. Scripts for npm do a good job for many projects which are not too complex. In the end that saves a lot of time and it will still work in two years :-)
